version: "3"

services:
  db:
    user: $UID
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_USERNAME: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/data/db
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh:ro
